batch_size: 128
grad_acc_steps: 1 # If we need to accumulated batches
eval_batch_size: null
learning_rate: 0.1
momentum: 0.9
main_optimizer: sgd
weight_decay: null
wd_mask: null # list of parameters type to exclude from wd
total_epochs: 250 # used to be total_steps: 97656
label_smoothing: 0.0 # smoothing applied over cross-entropy labels
test_eval_freq: 2000
add_train_eval: false # Record additional metrics on raw train dataset (no augmentation) at the same freq as test_eval
record_histograms: false # Record histogram over p(correct class) and per-sample NLL, for analysis purpose
checkpoint_freq: 1000 # Snapshot of model and training for preemption handling
logging_freq: 10 # Base logging freq for training losses etc. with aim
report_freq: 200 # Frequency (in steps) at which current training progress is reported in CLI
init_key: 42
rng_seed: 123 # For dropout, etc.

update_preconditioner_every: 1000
update_preconditioner_until: null
precond_rank: null
precond_identity_scaling: 1.0
precond_steps: 50
precond_batch_size: 64
precond_lr: 0.001
precond_solver: momentum
precond_on_update: false
precond_clip_norm: 5.0
precond_clip_element_wise: null
normalize_grad_for_lqr: false
normalize_conv_params: false
allow_grad_inversion: false
use_preconditioner: true
measure_asymmetry: false

divergence: ngd
divergence_order_param: 0.5
block_structure: diagonal
block_structure_init: identity
batch_solve_precond: true
llqr_operator_mode: cached_exact
llqr_checkpoint_policy: none
llqr_use_fast_paths: true
llqr_batch_experimental_mode: none
llqr_batch_chunk_size: null
llqr_second_order_mode: batched_exact
llqr_second_order_chunk_size: null
warm_start_precond: true
multibatch_training: false
damping: 0.0
ema_decay: 0.0 # EMA decay value for updating the preconditioner

# Cluster options
preempt_handling: false
jobid: null  # To manually restart a previous job

# SAM / Friendly-SAM training options
sam_mode: null # "base_fsam" | "past_fsam"
perturbation_rho: 0.1
perturb_mode: 'ema_grad' # "ema_grad" | "ema_precond_grad" | "ema_direction"
gbar_beta: 0.9
gbar_eps: 1e-12
batch_overlap_fraction: 0.0 #Roll-out strategy over minibatches, for past_fsam
